const data = {
    products:[
        {
            _id: '1',
            name: 'Product 1',
            category: 'Sauce',
            image: '/images/product-1.jpeg',
            price: 12,
            brand: "'Hank's",
            rating: 4.5,
            numReviews: 10,
            description: 'spicy nector of the gods',
        },
        {
            _id: '2',
            name: 'Product 2',
            category: 'Sauce',
            image: '/images/product-2.jpeg',
            price: 12,
            brand: "'Hank's",
            rating: 4.5,
            numReviews: 10,
            description: 'spicy nector of the gods',
        },
        {
            _id: '3',
            name: 'Product 3',
            category: 'Sauce',
            image: '/images/product-3.jpeg',
            price: 12,
            brand: "'Hank's",
            rating: 4.5,
            numReviews: 10,
            description: 'spicy nector of the gods',
        },
        {
            _id: '4',
            name: 'Product 4',
            category: 'Sauce',
            image: '/images/product-4.jpeg',
            price: 12,
            brand: "'Hank's",
            rating: 4.5,
            numReviews: 10,
            description: 'spicy nector of the gods',
        },
        {
            _id: '5',
            name: 'Product 5',
            category: 'Sauce',
            image: '/images/product-5.jpeg',
            price: 12,
            brand: "'Hank's",
            rating: 4.5,
            numReviews: 10,
            description: 'spicy nector of the gods',
        },
        {
            _id: '6',
            name: 'Product 6',
            category: 'Sauce',
            image: '/images/product-6.jpeg',
            price: 12,
            brand: "'Hank's",
            rating: 4.5,
            numReviews: 10,
            description: 'spicy nector of the gods',
        },
        {
            _id: '7',
            name: 'Product 7',
            category: 'Sauce',
            image: '/images/product-7.jpeg',
            price: 12,
            brand: "'Hank's",
            rating: 4.5,
            numReviews: 10,
            description: 'spicy nector of the gods',
        },
        {
            _id: '8',
            name: 'Product 8',
            category: 'Sauce',
            image: '/images/product-8.jpeg',
            price: 12,
            brand: "'Hank's",
            rating: 4.5,
            numReviews: 10,
            description: 'spicy nector of the gods',
        },

    ]
}